import Head from "next/head";
import Header from "../components/Header";
import { CheckCircleIcon } from "@heroicons/react/solid";
import { useRouter } from "next/router";

const Success = () => {
  const router = useRouter();

  return (
    <div className="h-screen bg-gray-100">
      <Head>
        <title>Success</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className="max-w-screen-lg mx-auto">
        <div className="flex flex-col p-10 bg-white">
          <div className="flex items-center space-x-2 mb-5">
            <CheckCircleIcon
              className="h-10"
              style={{
                color: "#059669",
              }}
            />
            <h1 className="text-3xl">
              Thank you, your order has been confirmed!
            </h1>
          </div>

          <p>
            Thank you for shopping with us. We&apos;ll send a confirmation once
            your item has shipped, if you would like to check the status of your
            order(s) please press the link below.
          </p>

          <button
            className="button"
            style={{
              marginTop: "1rem",
            }}
            onClick={() => router.push("/orders")}
          >
            Go to my orders
          </button>
        </div>
      </main>
    </div>
  );
};

export default Success;
